# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  ];
  nixpkgs.config.allowUnfree = true;
  hardware.enableAllFirmware = true;
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7f1a0a65-ae62-4c09-a20a-bed2e3f360b1";
    fsType = "ext4";
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3300-D74B";
    fsType = "vfat";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e3074361-8496-4584-9532-0eb0da9b264c"; }
  ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # High-DPI console

  hardware.pulseaudio.enable = true;
  hardware.bluetooth.enable = true;
  hardware.opengl.enable = true;
  
}
