{config,pkgs,lib,...}:
{
  environment.systemPackages = with pkgs; [
    wget 
    git 
    cachix 
    alacritty 
    spotifyd 
    gnome3.nautilus 
    gnome3.sushi 
    bashmount 
    ntfs3g 
    xclip 
    lastpass-cli 
    gnumake 
    obs-studio 
    lxqt.pavucontrol-qt 
    powerline-rs 
    ncurses 
    ncurses5
    zlib 
    stack
    cabal-install
    haskellPackages.hoogle
    haskellPackages.haddock
    nix-index
    docker-compose
    xdotool
    font-awesome
    freetype
    gcc
    glibc
    python
    unzip
    zip
    zoom-us
    direnv
    skypeforlinux
    rustup
  ];
}
