theme = "modern"
icons = "awesome"

[[block]]
block = "uptime"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB ({Mup}%)"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}%"

[[block]]
block = "load"
interval = 1
format = "{1m}"


[[block]]
block = "sound"
on_click = "pulsemixer --toggle-mute"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %I:%M"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %I:%M"
timezone = "US/Eastern"

[[block]]
block = "battery"
device = "BAT1"
