prompt() {
  PS1="$(powerline-rs --shell bash $?)"
}
PROMPT_COMMAND=prompt

HISTCONTROL=ignoreboth:erasedups HISTSIZE=100000 HISTFILESIZE=200000


#aliases
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias h='history'
alias j='jobs -l'
alias ..='cd ..'
alias du='du -kh' 
alias df='df -kTh'
alias l="ls -alh --color"
